version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: bd_lectum
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./baseDeDatos/bd_lectum.sql:/docker-entrypoint-initdb.d/bd_lectum.sql

volumes:
  db_data: